### ISSUE TITLE
Pod install not working with Rover

### ISSUE THREAD

**Issue by minhhieu052** [RoverPlatform/rover-ios#114]
Recently, I can not install the Rover on my project. I don't why it happen. In the past, it works well

Run pod install (I tried with other pod version and got the same problem)
I got this error as below

> Re-creating CocoaPods due to major version update.
> Analyzing dependencies
> [!] Unable to satisfy the following requirements:
> 
> Rover required by Podfile
> Rover (= 3.0.9) required by Podfile.lock
> None of your spec sources contain a spec satisfying the dependencies: Rover, Rover (= 3.0.9).
> 
> You have either:
> 
> out-of-date source repos which you can update with pod repo update.
> mistyped the name or version.
> not added the source repo that hosts the Podspec to your Podfile.
> Note: as of CocoaPods 1.0, pod repo update does not happen on pod install by default.

CocoaPods Environment

pod --version
1.0.1

I also run 'pod repo update' and pod install again. The issue is still happen
<img width="1133" alt="screen shot 2016-10-07 at 4 58 51 pm" src="https://cloud.githubusercontent.com/assets/4659476/19232437/f9201082-8f09-11e6-97d5-ec3dbe9a1c5f.png">

The other pod still download and working properly. I don't what happen with this lib recently

**Comment by seanrucker** [comment]
Hi @minhhieu052 it looks like you are using an old version of the Rover platform. 

In April this year we released a brand new Rover and notified our users that we would be sunsetting the existing product after 1-year time.

We have since removed the CocoaPod from the original product. If you are still relying on the deprecated SDK we can provide you with the source so you can get your project up and running. Please email support@rover.io.

Please note that the original Rover product will no longer function past March 2017 and you should consider transition to the new platform as soon as possible. You can register for a demo of the new platform on [the Rover website](https://www.rover.io/).

**Comment by minhhieu052** [comment]
Thanks your feedback
