### ISSUE TITLE
Poll Getting Cut Off

### ISSUE THREAD

**Issue by seanrucker** [RoverPlatform/rover-ios#523]
On the first screen of the experience with ID 5de84226b894fd000ad52be0 there is a poll at the bottom that is getting cut off on iOS. Android seems to be fine.

<img width="758" alt="Screen Shot 2020-01-07 at 10 33 14 AM" src="https://user-images.githubusercontent.com/188337/71907053-40e70400-3139-11ea-8695-663738a88a8b.png">

(Image has been redacted).

**Comment by orospakr** [comment]
The issue is that newlines in the question block are not being measured on iOS as counting towards poll block auto-height.  Workaround: remove any newlines in the question text.

<img width="925" alt="image" src="https://user-images.githubusercontent.com/16714/71929979-c46c1980-3168-11ea-8c7b-fc7ce80a7834.png">

Editor on left, SDK on right.

(minor related issue: the Experiences authoring app is not showing the newlines in the text in the preview)

**Comment by orospakr** [comment]
Indeed, it turns out that NSAttributedText.boundingRect is a bit buggy, and others have noticed this problem: https://stackoverflow.com/a/33697493/288557

**Comment by orospakr** [comment]
Using Core Text directly did not help.

**Comment by orospakr** [comment]
Shipped in 3.6.0.
